name: Periodic cluster integration tests
on:
  schedule:
  - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  integration-tests-dev:
    name: Cluster integration tests for dev
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Authenticate with Google Cloud platform
        uses: google-github-actions/auth@v0.5.0
        with:
          create_credentials_file: true
          cleanup_credentials: true
          credentials_json: ${{ secrets.CAPACT_GKE_CREDS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
      - name: Get cluster credentials
        run: |
          gcloud container clusters get-credentials ${CLUSTER_NAME} --zone europe-west1-b --project sm-cluster-dev
        env:
          CLUSTER_NAME: 'sm-dev'
      - name: Test Capact release
        run: |
          helm test capact --namespace=capact-system --timeout="30m" --logs

  integration-tests-stage:
    name: Cluster integration tests for stage
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Authenticate with Google Cloud platform
        uses: google-github-actions/auth@v0.5.0
        with:
          create_credentials_file: true
          cleanup_credentials: true
          credentials_json: ${{ secrets.CAPACT_GKE_CREDS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
      - name: Get cluster credentials
        run: |
          gcloud container clusters get-credentials ${CLUSTER_NAME} --zone europe-west1-b --project sm-cluster-dev
        env:
          CLUSTER_NAME: 'sm-stage'
      - name: Test Capact release
        run: |
          helm test capact --namespace=capact-system --timeout="30m" --logs

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [ integration-tests-dev, integration-tests-stage ]
    if: always()

    steps:
      - name: Slack Notification
        if: ${{ always() && needs.integration-tests-dev.result != 'success' || needs.integration-tests-stage.result != 'success' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: Capact CI Notifier
          SLACK_COLOR: 'red'
          SLACK_TITLE: 'Message'
          SLACK_CHANNEL: 'capact-dev-private'
          SLACK_MESSAGE: "GitHub build result: ${{ job.status }}\n}"
          SLACK_ICON_EMOJI: ':this-is-fine:'
          SLACK_FOOTER: "Hopefully it is not an error, it's gorgeous feature"
          SLACK_WEBHOOK: ${{ secrets.SLACK_PRIV_DEV_TEAM_WEBHOOK }}

