name: Periodic cluster integration tests
on:
  schedule:
  - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  integration-tests-dev:
    name: Cluster integration tests for dev
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Authenticate with Google Cloud platform
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          cleanup_credentials: true
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Get cluster credentials
        run: |
          gcloud container clusters get-credentials ${CLUSTER_NAME} --zone europe-west1-b --project sm-cluster-dev
        env:
          CLUSTER_NAME: 'sm-dev'
      - name: Test Capact release
        run: |
          helm test capact --namespace=capact-system --timeout="30m" --logs

  integration-tests-stage:
    name: Cluster integration tests for stage
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Authenticate with Google Cloud platform
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          cleanup_credentials: true
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Get cluster credentials
        run: |
          gcloud container clusters get-credentials ${CLUSTER_NAME} --zone europe-west1-b --project sm-cluster-dev
        env:
          CLUSTER_NAME: 'sm-stage'
      - name: Test Capact release
        run: |
          helm test capact --namespace=capact-system --timeout="30m" --logs
    
  integration-tests-kone:
    name: Cluster integration tests for kone
    runs-on: ubuntu-latest
    environment: kone
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Authenticate with Google Cloud platform
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          cleanup_credentials: true
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Get cluster credentials
        run: |
          gcloud container clusters get-credentials ${CLUSTER_NAME} --zone europe-west1-b --project sm-cluster-prod
        env:
          CLUSTER_NAME: 'sm-kone'
      - name: Test Capact release
        run: |
          helm test capact --namespace=capact-system --timeout="30m" --logs
  
  integration-tests-ibmlz:
    name: Cluster integration tests for ibmlz
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Authenticate with Google Cloud platform
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          cleanup_credentials: true
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Get cluster credentials
        run: |
          gcloud container clusters get-credentials ${CLUSTER_NAME} --zone europe-west1-b --project sm-cluster-dev
        env:
          CLUSTER_NAME: 'sm-ibmlz'
      - name: Test Capact release
        run: |
          helm test capact --namespace=capact-system --timeout="30m" --logs
    
  integration-tests-neste-dev:
    name: Cluster integration tests for neste dev
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Authenticate with Google Cloud platform
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          cleanup_credentials: true
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Get cluster credentials
        run: |
          gcloud container clusters get-credentials ${CLUSTER_NAME} --zone europe-west1-b --project sm-cluster-dev
        env:
          CLUSTER_NAME: 'sm-neste-dev'
      - name: Test Capact release
        run: |
          helm test capact --namespace=capact-system --timeout="30m" --logs

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [ integration-tests-dev, integration-tests-stage, integration-tests-kone, integration-tests-ibmlz, integration-tests-neste-dev ]
    if: always()

    steps:
      - name: Slack Notification
        if: ${{ needs.integration-tests-dev.result != 'success' || needs.integration-tests-stage.result != 'success' || needs.integration-tests-kone.result != 'success' || needs.integration-tests-ibmlz.result != 'success' || needs.integration-tests-neste-dev.result != 'success' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: SuperMaestro CI Notifier
          SLACK_COLOR: 'red'
          SLACK_TITLE: 'Message'
          SLACK_CHANNEL: 'pat-supermaestro-alert-notification'
          SLACK_MESSAGE: "Failed to run E2E"
          SLACK_ICON_EMOJI: ':this-is-fine:'
          SLACK_FOOTER: "Hopefully it is not an error, it's gorgeous feature"
          SLACK_WEBHOOK: ${{ secrets.SLACK_PRIV_DEV_TEAM_WEBHOOK }}
